In [40]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor


from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report

from sklearn.metrics import mean_squared_error, r2_score

from pickle import dump

import warnings
warnings.filterwarnings('ignore')

In [8]:
data_train = pd.read_csv('/workspaces/BOOSTING_ALGORITHMS_JesusCastanedam/data/processed/train_data.csv')
data_train

Pregnancies  Glucose   BMI  DiabetesPedigreeFunction  Age  Outcome
0              1      193  25.9                     0.655   24        0
1              1      143  30.1                     0.892   23        0
2              1      164  32.8                     0.341   50        0
3             12       84  29.7                     0.297   46        1
4             10      108  32.4                     0.272   42        1
..           ...      ...   ...                       ...  ...      ...
587            1       79  32.0                     0.396   22        0
588            1       89  31.2                     0.192   23        0
589            2      108  27.0                     0.259   52        1
590            5       86  30.2                     0.364   24        0
591            3       83  34.3                     0.336   25        0

[592 rows x 6 columns]

In [9]:
data_test = pd.read_csv('/workspaces/BOOSTING_ALGORITHMS_JesusCastanedam/data/processed/test_data.csv')
data_test

Pregnancies  Glucose   BMI  DiabetesPedigreeFunction  Age  Outcome
0              1      117  34.5                     0.403   40        1
1             12      140  37.4                     0.244   41        0
2              3       61  34.4                     0.243   46        0
3              3       81  27.5                     0.306   22        0
4              1       80  30.0                     0.527   22        0
..           ...      ...   ...                       ...  ...      ...
143           13      126  43.4                     0.583   42        1
144            8      105  43.3                     0.239   45        1
145            5      105  36.9                     0.159   28        0
146            0      180  42.0                     1.893   25        1
147            4      129  35.1                     0.231   23        0

[148 rows x 6 columns]

In [13]:
print('Tamaño del test:',data_test.shape)
print('\nTamaños del train:',data_train.shape)

Tamaño del test: (148, 6)

Tamaños del train: (592, 6)


In [14]:
X_test = data_test.drop('Outcome', axis=1)
X_train = data_train.drop('Outcome', axis=1)
y_train = data_train['Outcome']
y_test = data_test['Outcome']

print(X_test.shape)
print(X_train.shape)
print(y_test.shape)
print(y_train.shape)

(148, 5)
(592, 5)
(148,)
(592,)


# Boosting for classification

### XGBoost

In [25]:
model = XGBClassifier(n_estimators=17, max_depth=3, learning_rate=0.1, use_label_encoder=False, eval_metric='logloss')
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=17, n_jobs=None,
              num_parallel_tree=None, ...)

In [26]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1])

In [27]:
accuracy_score(y_test, y_pred)

0.7837837837837838

In [28]:
recall_score(y_test, y_pred)

0.55

In [30]:
# predicción
y_pred_test = model.predict(X_test)
y_pred_test

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1])

In [31]:
y_pred_train = model.predict(X_train)
y_pred_train

array([0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [33]:
# metricas
accuracy_test = accuracy_score(y_test, y_pred_test)
accuracy_train = accuracy_score(y_train, y_pred_train)

f1_score_test = f1_score(y_test, y_pred_test, )
f1_score_train = f1_score(y_train, y_pred_train, )

precision_test = precision_score(y_test, y_pred_test, )
precision_train = precision_score(y_train, y_pred_train, )

recall_test = recall_score(y_test, y_pred_test, )
recall_train = recall_score(y_train, y_pred_train, )

print("Accuracy Test: ", accuracy_test)
print("F1 score Test: ", f1_score_test)
print("Precision Test: ", precision_test)
print("Recall Test: ", recall_test)

print("\nAccuracy Train: ", accuracy_train)
print("F1 score Train: ", f1_score_train)
print("Precision Train: ", precision_train)
print("Recall Train: ", recall_train)

Accuracy Test:  0.7837837837837838
F1 score Test:  0.5789473684210527
Precision Test:  0.6111111111111112
Recall Test:  0.55

Accuracy Train:  0.7922297297297297
F1 score Train:  0.6702412868632708
Precision Train:  0.7861635220125787
Recall Train:  0.5841121495327103


In [34]:
print(classification_report(y_test, y_pred_test, target_names=["Diabetico", "No Diabetico"]))

              precision    recall  f1-score   support

   Diabetico       0.84      0.87      0.85       108
No Diabetico       0.61      0.55      0.58        40

    accuracy                           0.78       148
   macro avg       0.73      0.71      0.72       148
weighted avg       0.78      0.78      0.78       148



In [35]:
model.save_model("xgb_classifier_default_42.json")

### # Boosting for classification (all)

In [42]:
ada = AdaBoostClassifier(n_estimators=100, learning_rate=0.1, random_state=42)
gb = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)
xgb = XGBClassifier(n_estimators=100, learning_rate=0.1, random_state = 42, use_label_encoder=False, eval_metric='mlogloss')
lgb = LGBMClassifier(n_estimators=100, learning_rate=0.1, random_state = 42)

# entrenamiento
ada.fit(X_train, y_train)
gb.fit(X_train, y_train)
xgb.fit(X_train, y_train)
lgb.fit(X_train, y_train)

[LightGBM] [Info] Number of positive: 214, number of negative: 378
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000071 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 487
[LightGBM] [Info] Number of data points in the train set: 592, number of used features: 5
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.361486 -> initscore=-0.568918
[LightGBM] [Info] Start training from score -0.568918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best 

LGBMClassifier(random_state=42)

In [43]:
# predicción
ada_y_pred_test = ada.predict(X_test)
gb_y_pred_test = gb.predict(X_test)
xgb_y_pred_test = xgb.predict(X_test)
lgb_y_pred_test = lgb.predict(X_test)

ada_y_pred_train = ada.predict(X_train)
gb_y_pred_train = gb.predict(X_train)
xgb_y_pred_train = xgb.predict(X_train)
lgb_y_pred_train = lgb.predict(X_train)

In [45]:
# metricas
ada_accuracy_test = accuracy_score(y_test, ada_y_pred_test)
ada_accuracy_train = accuracy_score(y_train, ada_y_pred_train)

gb_accuracy_test = accuracy_score(y_test, gb_y_pred_test)
gb_accuracy_train = accuracy_score(y_train, gb_y_pred_train)

xgb_accuracy_test = accuracy_score(y_test, xgb_y_pred_test)
xgb_accuracy_train = accuracy_score(y_train, xgb_y_pred_train)

lgb_accuracy_test = accuracy_score(y_test, lgb_y_pred_test)
lgb_accuracy_train = accuracy_score(y_train, lgb_y_pred_train)

print('AdaBoost')
print("Accuracy Test: ", ada_accuracy_test)
print("Accuracy Train: ", ada_accuracy_train)

print('\nGradient Boosting')
print("Accuracy Test: ", gb_accuracy_test)
print("Accuracy Train: ", gb_accuracy_train)

print('\nXGBoost')
print("Accuracy Test: ", xgb_accuracy_test)
print("Accuracy Train: ", xgb_accuracy_train)

print('\nLightGBM')
print("Accuracy Test: ", lgb_accuracy_test)
print("Accuracy Train: ", lgb_accuracy_train)

AdaBoost
Accuracy Test:  0.7972972972972973
Accuracy Train:  0.7719594594594594

Gradient Boosting
Accuracy Test:  0.7702702702702703
Accuracy Train:  0.8986486486486487

XGBoost
Accuracy Test:  0.7702702702702703
Accuracy Train:  0.9949324324324325

LightGBM
Accuracy Test:  0.7837837837837838
Accuracy Train:  1.0
